# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbf48abbb1786cce9a1b432381cea572be3669b104bece07d28a81fedd998a3ede10c5c2de656265428a0e651db3c9dbd455acfc039c4d75fff6e8859b2bb36

test:
  secret_key_base: e385ae1eec96be642531c97244d0ee9ab6a96e9e94d6aaef21dff0a6d640f61afae4fdf756f5adca74fbefa54c3e5ee2cfbbb5ec02cd865cb9595ffe75b47415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
